# Generated by Django 5.1.1 on 2024-09-30 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='role',
            field=models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=10, verbose_name='Member role'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='share',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Share'),
        ),
    ]
